// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvcBqftZJQFsT-P2vlSPEVSkLnrfDCzu0',
    appId: '1:1018508576982:web:5b792cba1eb6debd0a6177',
    messagingSenderId: '1018508576982',
    projectId: 'inventree-d2560',
    authDomain: 'inventree-d2560.firebaseapp.com',
    storageBucket: 'inventree-d2560.appspot.com',
    measurementId: 'G-YTQNYNE21V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJWhyL0lXm7yq12PRiAPT0zQC0mf8YJ8',
    appId: '1:1018508576982:android:9fe8efee38c4e2810a6177',
    messagingSenderId: '1018508576982',
    projectId: 'inventree-d2560',
    storageBucket: 'inventree-d2560.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZCU-9ld_ZSKpPiLwcrKkaoDIaFAHYQ3o',
    appId: '1:1018508576982:ios:c045b3bf5b7675cd0a6177',
    messagingSenderId: '1018508576982',
    projectId: 'inventree-d2560',
    storageBucket: 'inventree-d2560.appspot.com',
    iosClientId: '1018508576982-raaoar0j73k27fg7jthoucn3tqdc9263.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZCU-9ld_ZSKpPiLwcrKkaoDIaFAHYQ3o',
    appId: '1:1018508576982:ios:c045b3bf5b7675cd0a6177',
    messagingSenderId: '1018508576982',
    projectId: 'inventree-d2560',
    storageBucket: 'inventree-d2560.appspot.com',
    iosClientId: '1018508576982-raaoar0j73k27fg7jthoucn3tqdc9263.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventree',
  );
}
